### ISSUE TITLE
v10: error when creating template (not blocked by default)

### ISSUE THREAD

**Issue by Weissrolf** [caewok/fvtt-walled-templates#12]
Ahoi. I get the following error when I create a template in v10 + PF2. As a result the template is not blocked by walls even though I set that as default via configuration.

module.js:302 Uncaught (in promise) TypeError: Cannot add property flags.walledtemplates.enabled, object is not extensible
[Detected 1 package: walledtemplates]
    at Object.fn (module.js:302:46)
    at #call (foundry.js:688:20)
    at Hooks.call (foundry.js:670:38)
    at ClientDatabaseBackend._preCreateDocumentArray (foundry.js:12367:47)
    at async ClientDatabaseBackend._createEmbeddedDocuments (foundry.js:12307:22)
(anonymous) @ module.js:302

**Comment by Weissrolf** [comment]
Reloading the browser switched the already created to being blocked by walls (as does manually switching it without reload). But the default wall-blocked creation throws the error.

**Comment by Weissrolf** [comment]
These error pop up when I open/close a door on the map (no template present):

module.js:190 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading '0')
[Detected 1 package: walledtemplates]
    at Object.fn (module.js:190:30)
    at #call (foundry.js:688:20)
    at Hooks.call (foundry.js:670:38)
    at ClientDatabaseBackend._preUpdateDocumentArray (foundry.js:12651:47)
    at async ClientDatabaseBackend._updateEmbeddedDocuments (foundry.js:12564:22)

module.js:250 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading '0')
[Detected 1 package: walledtemplates]
    at Object.fn (module.js:250:30)
    at #call (foundry.js:688:20)
    at Hooks.callAll (foundry.js:645:17)
    at ClientDatabaseBackend.callback (foundry.js:12745:13)
    at foundry.js:12713:43
    at Array.map (<anonymous>)
    at ClientDatabaseBackend._handleUpdateEmbeddedDocuments (foundry.js:12713:33)
    at ClientDatabaseBackend._updateEmbeddedDocuments (foundry.js:12575:17)
    at async WallDocument.updateDocuments (commons.js:5674:23)
    at async WallDocument.update (commons.js:5771:23)

**Comment by RinVindor** [comment]
Yeah having this issue as well.

**Comment by caewok** [comment]
Fixed in v0.4.2.
