### ISSUE TITLE
Error: undefined id [Dgu0C7CUX4cxN6kq] does not exist in the EmbeddedCollection collection.

### ISSUE THREAD

**Issue by strongpauly** [caewok/fvtt-walled-templates#50]
```
Uncaught (in promise) Error: undefined. undefined id [4aLcHjOU9YsClbh6] does not exist in the EmbeddedCollection collection. Token.js:76
[No packages detected]
    at EmbeddedCollection.get (file:///Applications/Foundry%20Virtual%20Tabletop.app/Contents/Resources/app/common/abstract/embedded-collection.mjs:164:36)
    at Scene.getEmbeddedDocument (file:///Applications/Foundry%20Virtual%20Tabletop.app/Contents/Resources/app/common/abstract/document.mjs:631:23)
    at fromUuid (file:///Applications/Foundry%20Virtual%20Tabletop.app/Contents/Resources/app/dist/core/utils.mjs:1:398)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

# Steps to reproduce

1. Create a template.
2. Attach it to a token.
3. Delete that token.

# Expected result
Template should be detached without error, or possibly should be deleted with the token - perhaps a dialog could pop up to allow the user to pick, or some flag could be assigned when the template is attached?

# Actual result
Error occurs shown in banner and in console.

Note: Error also occurs if you delete a token then try to attach a template to the last selected token.

**Comment by caewok** [comment]
Fixed in v0.6.7.
