### ISSUE TITLE
error on scene load, probably because of token no actor

### ISSUE THREAD

**Issue by dineshm72** [caewok/fvtt-walled-templates#65]
Uncaught (in promise) TypeError: Cannot read properties of null (reading 'effects')
    at Token5e.attachedTemplates (Token.js:229:21)
    at Object.destroyTokenHook [as fn] (Token.js:77:26)
    at #call (foundry.js:730:20)
    at Hooks.callAll (foundry.js:687:17)
    at Token5e.destroy (foundry.js:28377:11)
    at mn.destroy (index.js:126:1)
    at foundry.js:34838:42
    at Array.forEach (<anonymous>)
    at TokenLayer._tearDown (foundry.js:34838:27)
    at TokenLayer._tearDown (foundry.js:35341:18)
    at TokenLayer._tearDown (foundry.js:42377:18)
    at TokenLayer.tearDown (foundry.js:34826:16)
    at InterfaceCanvasGroup.tearDown (foundry.js:29592:21)
    at async Canvas.tearDown (foundry.js:26628:7)
    at async Canvas.draw (foundry.js:26498:9)
    at async Scene.view (foundry.js:23647:7)

mouse over indicates coming from walled templates
<img width="434" alt="image" src="https://github.com/caewok/fvtt-walled-templates/assets/2231877/cc55f455-2263-401f-8573-dc2045cf5fc7">

Probably an issue with a token with no actor.  After I cleaned those up the error seemed to disappear.  But you probably want to add some null checks.

**Comment by caewok** [comment]
Should be addressed in v0.6.10.
